version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app 
    command: sh -c "cd skill_sheet && yarn dev"
    ports:
      - "8090:8090" #port 指定