name: Run Jest

on:
  push:
  pull_request:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Yarn Install
        run: yarn install
        
      - name: Run test
        run: |
          docker-compose build
          docker-compose up --abort-on-container-exit
          docker-compose sh
        working-directory: ./skill_sheet
        run: docker-compose sh && yarn test