name: Run Jest

on:
  push:
     paths:
      - 'skill_sheet/**'
  pull_request:
     paths:
      - 'skill_sheet/**'

defaults:
  run:
    working-directory: skill_sheet

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Yarn Install
        run: yarn install
        
      - name: Run test
        run: yarn test